spring:
    application:
        name: jpahomework
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@//localhost:1521/xe
        username: c##idev
        password: 1234
    jpa:
        hibernate:
            ddl-auto: validate    #create, update, validate, none
        properties:
            '[format_sql]': true

logging:
    level:
        '[org.iclass]': debug
        '[org.hibernate.SQL]': debug
    pattern:
        console: '%clr(%-5level){yellow} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n'
